#!/usr/bin/env zsh
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do zsh -c "${installer}" ; done
